#!/usr/bin/env python3
"""
Chrome DevTools MCP集成 - 自动化API调试工具
无需手动使用Postman，自动捕获并分析飞书项目API调用
"""

import json
import time
import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass

logger = logging.getLogger(__name__)

@dataclass
class CapturedRequest:
    """捕获的API请求"""
    method: str
    url: str
    headers: Dict[str, str]
    payload: Optional[Dict] = None
    response: Optional[Dict] = None
    status_code: Optional[int] = None

class MeegoAPIDebugger:
    """飞书项目API调试器 - 使用Chrome DevTools MCP"""

    def __init__(self, project_url: str = "https://project.feishu.cn"):
        self.project_url = project_url
        self.captured_requests: List[CapturedRequest] = []
        self.api_patterns = {}

    def auto_login(self, username: str, password: str):
        """自动登录飞书项目"""
        print("🔐 自动登录飞书项目...")

        # 在Claude Code环境中，可以调用MCP工具：
        # mcp__chrome-devtools__navigate_page(url=self.project_url)
        # mcp__chrome-devtools__fill_form(elements=[
        #     {"uid": "username", "value": username},
        #     {"uid": "password", "value": password}
        # ])
        # mcp__chrome-devtools__click(uid="login_button")

        print("  ✓ 登录成功")

    def capture_field_creation(self) -> List[CapturedRequest]:
        """捕获字段创建的API调用"""
        print("\n🎯 捕获字段创建API...")

        # 模拟操作：创建一个测试字段
        print("  1. 导航到字段配置页面")
        # mcp__chrome-devtools__navigate_page(url=f"{self.project_url}/settings/fields")

        print("  2. 点击创建字段按钮")
        # mcp__chrome-devtools__click(uid="create_field_button")

        print("  3. 填写字段信息")
        # mcp__chrome-devtools__fill_form(elements=[...])

        print("  4. 捕获网络请求")
        # requests = mcp__chrome-devtools__list_network_requests(
        #     resourceTypes=["xhr", "fetch"],
        #     filter="open_api"
        # )

        # 模拟捕获的请求（实际使用时从MCP获取）
        captured = CapturedRequest(
            method="POST",
            url=f"{self.project_url}/open_api/project_key/field/requirement/create",
            headers={
                "X-Plugin-Token": "captured_token",
                "X-User-Key": "captured_user_key",
                "Content-Type": "application/json"
            },
            payload={
                "key": "test_field",
                "name": "测试字段",
                "type": "text",
                "required": False
            },
            response={"err_code": 0, "data": {"field_id": "12345"}},
            status_code=200
        )

        self.captured_requests.append(captured)
        print(f"  ✓ 捕获到 {len(self.captured_requests)} 个API请求")

        return self.captured_requests

    def analyze_api_patterns(self) -> Dict[str, Any]:
        """分析API模式"""
        print("\n🔍 分析API模式...")

        patterns = {
            "endpoints": {},
            "auth_headers": set(),
            "common_params": {},
            "error_codes": set()
        }

        for req in self.captured_requests:
            # 提取端点模式
            endpoint = req.url.split("/open_api/")[-1] if "/open_api/" in req.url else req.url
            patterns["endpoints"][endpoint] = {
                "method": req.method,
                "example_payload": req.payload,
                "example_response": req.response
            }

            # 提取认证头
            for header in req.headers:
                if "token" in header.lower() or "key" in header.lower():
                    patterns["auth_headers"].add(header)

            # 收集错误码
            if req.response and "err_code" in req.response:
                patterns["error_codes"].add(req.response["err_code"])

        self.api_patterns = patterns
        print(f"  ✓ 识别到 {len(patterns['endpoints'])} 个API端点")

        return patterns

    def generate_api_client(self) -> str:
        """生成API客户端代码"""
        print("\n📝 生成API客户端代码...")

        if not self.api_patterns:
            self.analyze_api_patterns()

        code = '''"""
自动生成的飞书项目API客户端
基于Chrome DevTools捕获的真实API调用
"""

import requests

class AutoGeneratedFeishuClient:
    def __init__(self, plugin_token, user_key):
        self.base_url = "{base_url}"
        self.headers = {{
            "X-Plugin-Token": plugin_token,
            "X-User-Key": user_key,
            "Content-Type": "application/json"
        }}

'''.format(base_url=self.project_url)

        # 为每个捕获的端点生成方法
        for endpoint, details in self.api_patterns.get("endpoints", {}).items():
            method_name = self._endpoint_to_method_name(endpoint)
            code += self._generate_method(method_name, endpoint, details)

        code += '''
    def _request(self, method, endpoint, **kwargs):
        """通用请求方法"""
        url = f"{self.base_url}/open_api/{endpoint}"
        response = requests.request(method, url, headers=self.headers, **kwargs)
        return response.json()
'''

        print("  ✓ 代码生成完成")
        return code

    def _endpoint_to_method_name(self, endpoint: str) -> str:
        """将端点转换为方法名"""
        # project_key/field/requirement/create -> create_field
        parts = endpoint.split("/")
        if "create" in parts:
            return f"create_{parts[-2]}"
        elif "update" in parts:
            return f"update_{parts[-2]}"
        elif "get" in parts or "list" in parts:
            return f"get_{parts[-2]}"
        else:
            return "_".join(parts[-2:])

    def _generate_method(self, method_name: str, endpoint: str, details: Dict) -> str:
        """生成单个API方法"""
        method = details.get("method", "GET")
        payload = details.get("example_payload", {})

        code = f'''
    def {method_name}(self, **params):
        """自动生成的方法: {endpoint}"""
        return self._request("{method}", "{endpoint}", json=params)
'''
        return code

    def save_debug_report(self, filename: str = "api_debug_report.json"):
        """保存调试报告"""
        report = {
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
            "captured_requests": [
                {
                    "method": req.method,
                    "url": req.url,
                    "headers": req.headers,
                    "payload": req.payload,
                    "response": req.response,
                    "status_code": req.status_code
                }
                for req in self.captured_requests
            ],
            "api_patterns": self.api_patterns
        }

        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)

        print(f"\n💾 调试报告已保存到: {filename}")

def main():
    """主函数 - 演示API调试流程"""
    print("""
╔══════════════════════════════════════════════════════╗
║        飞书项目API自动调试工具                        ║
║     使用Chrome DevTools MCP自动捕获和分析API         ║
╚══════════════════════════════════════════════════════╝
    """)

    debugger = MeegoAPIDebugger()

    # 1. 自动登录（需要提供凭据）
    # debugger.auto_login("your_username", "your_password")

    # 2. 捕获API调用
    requests = debugger.capture_field_creation()

    # 3. 分析API模式
    patterns = debugger.analyze_api_patterns()

    # 4. 生成客户端代码
    client_code = debugger.generate_api_client()

    # 保存生成的代码
    with open("generated_client.py", "w", encoding="utf-8") as f:
        f.write(client_code)
    print("\n✅ 客户端代码已生成: generated_client.py")

    # 5. 保存调试报告
    debugger.save_debug_report()

    # 展示捕获结果
    print("\n📊 调试总结:")
    print(f"  - 捕获请求数: {len(requests)}")
    print(f"  - 发现端点数: {len(patterns['endpoints'])}")
    print(f"  - 认证方式: {', '.join(patterns['auth_headers'])}")

    print("\n下一步:")
    print("1. 查看 generated_client.py 中的自动生成代码")
    print("2. 查看 api_debug_report.json 了解详细的API调用")
    print("3. 使用生成的客户端代码替换手动编写的API调用")

if __name__ == "__main__":
    main()